# Generated by Django 5.2.17 on 2026-10-02 05:18

from django.db import migrations, models

# Fixed copy of accounts.access.STAFF_BEFORE_SWITCHES at the time of this migration.
STAFF_BEFORE_SWITCHES = [
    "billing", "payments", "purchases", "add_items", "count_stock", "view_bills", "view_khata", "view_sales",
]


def keep_what_staff_could_do(apps, schema_editor):
    """Existing staff keep every daily job and seeing switch, exactly what they could do before."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="staff").update(access=STAFF_BEFORE_SWITCHES)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Switches the owner turned on (staff only).",
            ),
        ),
        migrations.RunPython(keep_what_staff_could_do, migrations.RunPython.noop),
    ]
