# Generated by Django 5.2.17 on 2026-10-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("count", "Stock count"),
                    ("purchase", "Purchase"),
                    ("sale", "Sale"),
                    ("sale_return", "Sale return"),
                    ("sale_cancelled", "Bill cancelled"),
                    ("purchase_return", "Return to supplier"),
                    ("adjustment", "Adjustment"),
                ],
                max_length=20,
            ),
        ),
    ]
