# Generated by Django 5.2.17 on 2026-10-01 10:47

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "1.5 sq mm Red". Blank if no variants.',
                        max_length=120,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Short code for items without a barcode.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(
                        choices=[
                            ("pc", "Piece"),
                            ("m", "Metre"),
                            ("ft", "Foot"),
                            ("kg", "Kilogram"),
                            ("l", "Litre"),
                            ("set", "Set"),
                            ("pair", "Pair"),
                            ("pkt", "Packet"),
                            ("roll", "Roll"),
                        ],
                        default="pc",
                        max_length=4,
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="MRP",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per base unit, GST included.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Weighted average purchase cost per base unit, GST excluded.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "stock_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=12,
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("rack", models.CharField(blank=True, max_length=30)),
                (
                    "aliases",
                    models.CharField(
                        blank=True,
                        help_text="Other names customers use, comma separated.",
                        max_length=250,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "counted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("needs_recount", models.BooleanField(default=False, editable=False)),
                ("search_text", models.TextField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["product__name", "variant"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="brand_name_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ItemUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="How many base units in one of this unit.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                ("is_base", models.BooleanField(default=False, editable=False)),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price for this whole pack, GST included. Blank = base price × size.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "ordering": ["factor"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(\\d{4}|\\d{6}|\\d{8})$",
                                "HSN code is 4, 6 or 8 digits.",
                            )
                        ],
                        verbose_name="HSN code",
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "0%"),
                            (Decimal("5"), "5%"),
                            (Decimal("12"), "12%"),
                            (Decimal("18"), "18%"),
                            (Decimal("28"), "28%"),
                            (Decimal("40"), "40%"),
                        ],
                        decimal_places=2,
                        default=Decimal("18"),
                        max_digits=4,
                        verbose_name="GST %",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="catalog.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="category_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemunit",
            constraint=models.UniqueConstraint(
                models.F("item"),
                django.db.models.functions.text.Lower("name"),
                name="item_unit_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemunit",
            constraint=models.UniqueConstraint(
                models.F("item"),
                condition=models.Q(("is_base", True)),
                name="item_single_base_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemunit",
            constraint=models.CheckConstraint(
                condition=models.Q(("factor__gt", 0)), name="item_unit_factor_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                models.F("brand"),
                django.db.models.functions.text.Lower("name"),
                name="product_brand_name_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["rack"], name="catalog_ite_rack_658677_idx"),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                models.F("product"),
                django.db.models.functions.text.Lower("variant"),
                name="item_product_variant_unique",
            ),
        ),
    ]
