# Generated by Django 5.2.17 on 2026-10-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemunit",
            name="mrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="MRP of the whole pack.",
                max_digits=12,
                null=True,
                verbose_name="MRP",
            ),
        ),
    ]
