# Generated by Django 5.2.17 on 2026-10-01 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Hindustan Electric", max_length=120),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{2}[A-Z0-9]{13}$",
                                "GSTIN must be 15 characters: 2-digit state code followed by 13 letters/digits.",
                            )
                        ],
                        verbose_name="GSTIN",
                    ),
                ),
                (
                    "state_code",
                    models.CharField(
                        default="10",
                        help_text="GST state code of the shop. Bihar is 10.",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{2}$", "State code is two digits."
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("bank_branch", models.CharField(blank=True, max_length=120)),
                ("bank_account_number", models.CharField(blank=True, max_length=30)),
                (
                    "bank_ifsc",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="Bank IFSC"
                    ),
                ),
                (
                    "invoice_terms",
                    models.TextField(
                        blank=True,
                        help_text="Printed at the bottom of every bill, one term per line.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "shop settings",
                "verbose_name_plural": "shop settings",
            },
        ),
    ]
