# Generated by Django 5.2.17 on 2026-10-01 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="invoice_prefix",
            field=models.CharField(
                default="HE",
                help_text="Start of every invoice number, e.g. HE → HE/26-27/00001. Letters and digits only.",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9]{1,4}$", "1 to 4 capital letters or digits."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="round_off_bills",
            field=models.BooleanField(
                default=True, help_text="Round bill totals to the nearest rupee."
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="upi_id",
            field=models.CharField(
                blank=True,
                help_text="If set, bills show a QR code to pay by UPI.",
                max_length=60,
                verbose_name="UPI ID",
            ),
        ),
    ]
