# Generated by Django 5.2.17 on 2026-10-01 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cancel_reason",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="payment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("opening", "Opening balance"),
                    ("bill", "Bill"),
                    ("payment", "Payment"),
                    ("bill_cancelled", "Bill cancelled"),
                    ("refund", "Payment returned"),
                    ("return", "Goods returned"),
                    ("receipt_cancelled", "Receipt cancelled"),
                    ("adjustment", "Adjustment"),
                ],
                max_length=20,
            ),
        ),
    ]
