import logging
import random
from flask import Blueprint, request, jsonify
from ..db_config import get_db
from datetime import datetime
from flask_jwt_extended import jwt_required, get_jwt_identity

invoice_bp = Blueprint("inventory_invoice", __name__)
logger = logging.getLogger(__name__)

@invoice_bp.route("/generate-invoice", methods=["POST"])
@jwt_required()
def generate_invoice():
    try:
        data = request.json
        supplier = data.get("supplier")
        if not all(k in supplier for k in ["name", "gstin", "address"]):
            return jsonify({"success": False, "message": "Incomplete supplier information."}), 400

        date_str = data.get("date_of_issuance")
        items = data.get("items", [])
        if not date_str or not items:
            return jsonify({"success": False, "message": "Date of issuance and items are required."}), 400
        
        try:
            date_of_issuance = datetime.strptime(date_str, "%Y-%m-%d")
        except ValueError:
            return jsonify({"success": False, "message": "Invalid date format. Expected YYYY-MM-DD."}), 400

        invoice_total = sum(float(item.get("total", 0)) for item in items)
        
        # Note: Using a robust, sequential invoice number is recommended over random.
        invoice_number = str(random.randint(10**15, 10**16 - 1))
        current_user = get_jwt_identity()

        invoice_data = {
            "invoice_number": invoice_number,
            "supplier": supplier,
            "recipient": data.get("recipient", {}),
            "date_of_issuance": date_of_issuance,
            "items": items,
            "invoice_total": invoice_total,
            "billing_address": data.get("billing_address", ""),
            "shipping_address": data.get("shipping_address", ""),
            "charge_type": data.get("charge_type", "forward"),
            "signature": data.get("signature", ""),
            "created_at": datetime.utcnow(),
            "created_by": current_user,
        }

        db = get_db()
        result = db["invoices"].insert_one(invoice_data)
        
        # Return the saved data, ensuring ObjectID is converted to string
        invoice_data["_id"] = str(result.inserted_id)
        invoice_data["date_of_issuance"] = date_of_issuance.isoformat()
        invoice_data["created_at"] = invoice_data["created_at"].isoformat()


        logger.info(f"Invoice {invoice_number} generated by user {current_user}")
        return jsonify({"success": True, "message": "Invoice generated successfully.", "invoice": invoice_data}), 200
    except Exception as e:
        logger.error(f"Error generating invoice: {str(e)}")
        return jsonify({"success": False, "message": "Failed to generate invoice."}), 500